import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'

export default function Chakra() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Chakra UI !
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/Chakra/Zenn">
            <a className={styles.card}>
              <h2>Zenn &rarr;</h2>
              <p>Zenn clone</p>
            </a>
          </Link>

          <Link href="/Chakra/Responsive">
            <a className={styles.card}>
              <h2>Responsive &rarr;</h2>
              <p>レスポンシブの練習してみる</p>
            </a>
          </Link>

          <Link href="/Chakra/Color">
            <a className={styles.card}>
              <h2>Color &rarr;</h2>
              <p>ダークモードも簡単に実装できるっぽい</p>
            </a>
          </Link>

          <Link href="/Chakra/Stack">
            <a className={styles.card}>
              <h2>Stack &rarr;</h2>
              <p>Stackでコンテンツをつくろう</p>
            </a>
          </Link>

          <Link href="/Chakra/Freedom">
            <a className={styles.card}>
              <h2>Freedom &rarr;</h2>
              <p>自由帳。なにしてもいい</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
